Foncardaz, Karl Friedrich E.

# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [ ]:
import numpy as np

#### 2. Print the numpy version

In [ ]:
import numpy as np

print(np.__version__)

#### 3. Create a null array of size 5

In [4]:
import numpy as np

arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [5]:
import numpy as np

arr = np.zeros(15)
arr[6] = 1
print(arr)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [11]:
import numpy as np

arr = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])

print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [13]:
import numpy as np

arr = np.array([1,2,4,0,4,0])

print(np.where(arr != 0))

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [17]:
import numpy as np 

arr = np.random.randint(100, size=(4,4,4))

print(arr)

[[[ 2 17 60 58]
  [28 12 15 25]
  [27 21 26 34]
  [ 2 23 13 12]]

 [[ 9 24 62 57]
  [46 62 17 40]
  [35  4  5 27]
  [18 40 57 53]]

 [[51 33 46 60]
  [ 0 12 57  3]
  [62 39 51 41]
  [14 44 41 41]]

 [[29 21 28  1]
  [62  1 59 32]
  [57 51 14 54]
  [10 55 32 34]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [24]:
import numpy as np 

arr = np.random.randint(100, size=(15,15))

print(arr)
print(np.min(arr))
print(np.max(arr))

[[50 28 17 10 77 83 51 92 85 36 62 52 64 27  8]
 [53 86 58 15 76 23 58 33 27 27 24 41 52 15 26]
 [44 25 34 50  2 64  3 57 99 57 31 56 45 77 12]
 [88 63 18 36 85 23 13 77 47 35 90 92 67 53 78]
 [79 57 11 40 45 45 23 18 54 58 97  4 44 68 26]
 [73 79 25 27 97 65 78 81 45 16 94 62 87 15 72]
 [13 76 16 80 30 60 16 91 90 72 88 20 76 29 52]
 [50 23 55 73 35 41 12 54 27 32 91 60 32 39  5]
 [87 60 25 29 63 95  6 95 59 79 37  3 74  6 30]
 [51 90 58 78  9 72 30 99 81 67 84 80 67 99 15]
 [77 83 86 92 82 95 34 44 20 97 49 38 71 10 58]
 [64 79  7 78 97 83 15 18 73 54 69 42 92 93 38]
 [80 91 59 90 95 91 27 46 66 95 84 86 20  8 22]
 [73  5 61 25  9 65 56 10 64 63 31 22 77 79 84]
 [25 38 58  0  4 27 31 82 19 58 44 48 75 67 62]]
0
99


#### 9. Create a random array of size 25 and find the mean value

In [25]:
import numpy as np 

arr = np.random.randint(100, size=(25))

print(np.mean(arr))

52.84


#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [32]:
import numpy as np 

arr_1 = np.array([2,4,9])
arr_2 = np.array([1,14,6])

print(arr_1)
print(arr_2)

[2 4 9]
[ 1 14  6]


10.1 What is the result of *a + b*?

In [33]:
import numpy as np 

arr_1 = np.array([2,4,9])
arr_2 = np.array([1,14,6])

print(np.add(arr_1, arr_2))

[ 3 18 15]


10.2 What is the result of *a - b*?

In [35]:
import numpy as np 

arr_1 = np.array([2,4,9])
arr_2 = np.array([1,14,6])

print(np.subtract(arr_1, arr_2))

[  1 -10   3]


10.3 What is the result of *a × b*?

In [36]:
import numpy as np 

arr_1 = np.array([2,4,9])
arr_2 = np.array([1,14,6])

print(np.multiply(arr_1, arr_2))

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [37]:
import numpy as np 

arr_1 = np.array([2,4,9])
arr_2 = np.array([1,14,6])

print(np.divide(arr_1, arr_2))

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [38]:
import numpy as np

arr = np.array([[10,20,30], [40,50,60], [70,80,90]])

print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [44]:
import numpy as np

arr = np.array([[10,20,30], [40,50,60], [70,80,90]])

print(arr[1,1])

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [42]:
import numpy as np

arr = np.array([[10,20,30], [40,50,60], [70,80,90]])

extracted_arr = arr[1]

print(extracted_arr)

[40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [53]:
import numpy as np

arr = np.array([[10,20,30], [40,50,60], [70,80,90]])

extracted_arr = arr[:, 2]

print(extracted_arr)

[30 60 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [54]:
import numpy as np

arr = np.array([[10,20,30], [40,50,60], [70,80,90]])

extracted_arr = arr[1:3, 1:3]

print(extracted_arr)

[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [55]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])


print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [56]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

extracted_arr = arr[1:3, 1:3]

print(extracted_arr)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [58]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

extracted_arr = arr[0, ::2]

print(extracted_arr)

[1 3]


4. Write code to reverse the order of rows in the matrix

In [59]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

extracted_arr = arr[::-1]

print(extracted_arr)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


5. Write code to extract the last two columns of the matrix.

In [62]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

extracted_arr = arr[:, 2:4]

print(extracted_arr)

[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [63]:
import numpy as np

arr_1 = np.array([11, 7, 33])
arr_2 = np.array([44, 5, 18])


print(arr_1)
print(arr_2)

[11  7 33]
[44  5 18]


2. Write code to join arr1 and arr2 into a single 1D array.

In [66]:
import numpy as np

arr_1 = np.array([11, 7, 33])
arr_2 = np.array([44, 5, 18])

print(np.concatenate((arr_1, arr_2)))

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [73]:
import numpy as np

arr_1 = np.array([11, 7, 33])
arr_2 = np.array([44, 5, 18])

print(np.stack((arr_1, arr_2), axis=0))

[[11  7 33]
 [44  5 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [74]:
import numpy as np

arr_1 = np.array([[1, 2], [3,4]])
arr_2 = np.array([[5, 6],[7,8]])

print(arr_1)
print(arr_2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


5. Write code to join them horizontally (column-wise).

In [79]:
import numpy as np

arr_1 = np.array([[1, 2], [3,4]])
arr_2 = np.array([[5, 6],[7,8]])

print(np.hstack((arr_1, arr_2)))

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [80]:
import numpy as np

arr_1 = np.array([[1, 2], [3,4]])
arr_2 = np.array([[5, 6],[7,8]])

print(np.vstack((arr_1, arr_2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [91]:
import numpy as np

arr1D = np.array([10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28])
arr1D = arr1D[::2]

arr2D = np.random.randint(50, size=(4,4))

arr3D = np.full((2,3,4), 1)

print(arr1D)
print(arr2D)
print(arr3D)


[10 12 14 16 18 20 22 24 26 28]
[[ 7 15 49  6]
 [ 9 18 16 25]
 [ 9  8  0 48]
 [26 12 15 12]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [168]:
import numpy as np

arr1 = np.array([10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28])
arr1 = arr1[::2]


arr2D = np.random.randint(50, size=(4,4))

print('1D array to a 2D array')
print(np.vstack((arr1, arr1)))

print('')

print('2d reference')
print(arr2D)

print('')

print('last two rows')
print(arr2D[2:4])

print('')

arr2D[arr2D % 2 == 0] = -1

print('replacing all even numbers with -1')
print(arr2D)




1D array to a 2D array
[[10 12 14 16 18 20 22 24 26 28]
 [10 12 14 16 18 20 22 24 26 28]]

2d reference
[[ 1  2  8 21]
 [21 41 21 12]
 [49  6 31 20]
 [ 7 38 34 13]]

last two rows
[[49  6 31 20]
 [ 7 38 34 13]]

replacing all even numbers with -1
[[ 1 -1 -1 21]
 [21 41 21 -1]
 [49 -1 31 -1]
 [ 7 -1 -1 13]]


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [171]:
import numpy as np

arr2D = np.random.randint(50, size=(4,4))
arr2DSum = np.array([np.sum(arr2D[0,:]), np.sum(arr2D[1,:]), np.sum(arr2D[2,:]), np.sum(arr2D[3,:])])

print('2D reference')
print(arr2D)
print()
print('Mean: ', np.mean(arr2D))
print('Median: ', np.median(arr2D))
print('Standard Dev.: ', np.std(arr2D))

print('')

print('sum of all elements along each row:')
print(arr2DSum)

print('')
print('largest value: ', np.max(arr2D))
print(np.where(arr2D == np.max(arr2D)))

2D reference
[[ 1  3 15 14]
 [36 14 42 23]
 [26 27  5 32]
 [18  4 40 24]]

Mean:  20.25
Median:  20.5
Standard Dev.:  12.808688457449499

sum of all elements along each row:
[ 33 115  90  86]

largest value:  42
(array([1]), array([2]))


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.

In [166]:
import numpy as np 

arr = np.random.rand(10,10)

print(arr,'\n')

for x in range(10):
    print(np.min(arr[x,:]))

arrnew = np.sort(np.concat(arr))

print('\n Top 5 largest Values:')

for x in range(5):
    print(x+1, ': ', arrnew[-(x+1)], ' ', np.where(arr == arrnew[-(x+1)]))
    # print(np.where(arr == arrnew[-(x+1)]))




[[9.48222422e-02 1.43626615e-01 3.82733033e-01 2.86957907e-04
  8.78904339e-01 2.25639031e-01 5.12400334e-02 4.46525494e-01
  6.02054641e-01 3.49310187e-01]
 [8.79175728e-01 8.16696143e-01 8.29386074e-01 9.57160408e-02
  4.66894962e-01 1.01543282e-01 8.86254823e-01 1.97062536e-01
  3.46966184e-01 6.13345057e-01]
 [8.78110350e-01 2.77928271e-02 8.35360357e-01 9.47504286e-01
  9.75635755e-01 9.05917824e-01 1.11974037e-01 2.86334497e-01
  1.56374920e-01 2.66060891e-01]
 [8.34445406e-01 7.32214328e-01 9.39188940e-01 9.15843165e-01
  9.42327802e-01 7.56927825e-01 8.71887969e-01 4.97885893e-01
  1.84230389e-01 7.71047413e-01]
 [6.16307684e-01 4.50481585e-01 9.94620073e-02 6.82781931e-01
  7.14183047e-01 6.79850383e-01 5.98191921e-01 4.78913760e-01
  8.23259597e-01 6.90235506e-01]
 [9.38274738e-01 2.54422434e-02 4.20715809e-01 3.19189660e-01
  2.56609660e-01 1.26938992e-01 5.25497468e-01 1.06980256e-01
  3.43663502e-01 2.58047755e-01]
 [2.83536835e-01 9.77868613e-01 3.87674782e-01 5.41688481e